---

# Configure tasks

- name: 'Generate ntp config file'
  become: True
  template:
    src: "{{ role_path }}/templates/ntp.conf.j2"
    dest: "{{ ntp_config_file_dest }}"
    owner: "{{ ntp_config_file_owner }}"
    group: "{{ ntp_config_file_group }}"
    mode: "{{ ntp_config_file_mode }}"
  notify: 'Restart ntp'


- name: 'Enable ntp service on boot'
  become: True
  service:
    name: "{{ ntp_service_name }}"
    enabled: "{{ ntp_service_enabled }}"
    state: "{{ ntp_service_state }}"
