---

# RedHat install tasks

- name: 'INSTALL | YUM | Install packages'
  become: True
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ ntp_packages }}"
  notify: 'HANDLER | Restart ntp'
