---

# Tasks file for ntp

- name: 'Load the OS specific variables'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'ntp::role'
    - 'ntp::config'
    - 'ntp::install'


- include: 'install_debian.yml'
  when: "{{ (ansible_os_family | lower)== 'debian' }}"
  tags:
    - 'ntp::role'
    - 'ntp::install'


- include: 'configure.yml'
  tags:
    - 'ntp::role'
    - 'ntp::config'
