---

# Role tests

- name: 'Converge | Prerequisites tasks on Debian OS family'
  hosts: 'all:!ntp-docker-centos7'
  gather_facts: False
  tasks:
    - name: 'PREREQUISITES | APT | Do an apt-get update'
      become: True
      raw: 'apt-get update -qq'
      changed_when: False
    - name: 'PREREQUISITES | APT | Install python 2.7 and iproute'
      become: True
      raw: 'apt-get install -qq python2.7 iproute2'
      changed_when: False


- name: 'Converge | Prerequisites tasks on Redhat OS family'
  hosts: 'ntp-docker-centos7'
  gather_facts: False
  tasks:
    - name: 'PREREQUISITES | YUM | Install iproute net-tools'
      become: True
      raw: 'yum install -qy iproute net-tools'
      changed_when: False


- name: 'Converge | Main tasks'
  hosts: 'all'
  roles:
    - role: "ansible-role-ntp"
